# Generated by Django 3.0.7 on 2020-10-19 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilvehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilvehiculo',
            name='chasis',
            field=models.CharField(error_messages={'unique': 'Chasis ya existe'}, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Requiere 17 digitos alfanumericos', regex='\\w[A-Z0-9]$')], verbose_name='Numero de Chasis'),
        ),
        migrations.AlterField(
            model_name='perfilvehiculo',
            name='matricula',
            field=models.CharField(error_messages={'unique': 'Matricula ya existe'}, max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Requiere 6 digitos y una letra mayuscula', regex='\\w[A-Z0-9]$')], verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='perfilvehiculo',
            name='motor',
            field=models.CharField(error_messages={'unique': 'Motor ya existe'}, max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Requiere 6 digitos y una letra mayuscula', regex='\\w[A-Z0-9]$')], verbose_name='Motor'),
        ),
    ]
