# Generated by Django 3.0.7 on 2020-10-19 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfilempresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilempresa',
            name='estatus',
            field=models.CharField(choices=[('N', 'Normalizado'), ('I', 'Investigacion'), ('C', 'Clausurada')], max_length=1, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='logopinture',
            field=models.ImageField(blank=True, upload_to='static/logos', verbose_name='Logo Empresa'),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='nombre',
            field=models.CharField(help_text='Registrar Nombre empresa', max_length=255, unique=True, verbose_name='Nombr Empresa'),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
